### PR TITLE
[WIP] Support for host variable #28

### PR DESCRIPTION
**Pull request by amandahla**
This is my first time working with Grafana plugin, any help would be most welcome.

In this first version, the user set "host" in query field to obtain all host in all sites as a variable. This way, is possible to create a predefined graph setting "$host" in "Host" field to get the values available.

image

image

### CODE REVIEW

**Comment by ruohki** [comment]
Does this work with other variables too. That are pulled in from other sources?

**Comment by amandahla** [comment]
@ruohki I didn't test this but I believe that it would work. Can you check, please?

**Comment by ruohki** [comment]
Yeh will do, asap cannot build the plugin in our environment because of proxies n stuff

Von meinem iPhone gesendet

**Comment by amandahla** [comment]
@ruohki I'm not sure if this is your idea, but I have tried with a variable from MySQL datasource and it works fine.

image

**Comment by ruohki** [comment]
Does this commit break the default combo box? Because i cannot select a host anymore - just a textbox

**Pull request closed without merging**
